### ISSUE TITLE
Xaero's maps has a bad UI

### ISSUE THREAD

**Issue by ejm554** [ejm554/gaia-modpack#1]
## Overview
- The main Xaero's Maps mod has a bad UI, especially when reviewing settings or working with waypoints.
- This mod integrates with other mods from the same developer, such as Xaero's Minimap and a claims/party mod.
- Better map mods are available, albeit also imperfect.

## To-Do
- [x] Delete/disable all the "Xaero's" mods (map/minimap/claims/etc.)
- [x] Add the JourneyMap mod
- [x] Remove other Xaero's-related artifacts (see screenshot)

## Also Consider
- [x] Consider adding a replacement mod for claiming areas. [^1]

### Folders in `.minecraft`
![image](https://user-images.githubusercontent.com/26723535/199066923-8c53b8ff-569e-46a6-9efd-021056942f46.png)

[^1]: This may not be needed; the Flan mod, which is designed for claiming, is already part of the modpack.
