### ISSUE TITLE
Consider mods: Secret Rooms, The Undergarden, and Castle in the Sky

### ISSUE THREAD

**Issue by ejm554** [ejm554/gaia-modpack#13]
## Overview
- A player has proposed that we add three mods to our modpack.
   - Secret Rooms
   - The Undergarden
   - Castle in the Sky

## To-Do
- [x] Test mods in a local world (containing only these instances)
- [x] Test 'Secret Rooms' in an updated modpack.
- [x] Test 'The Undergarden' in an updated modpack. [^1]
- [x] Test 'Castle in the Sky' in an updated modpack.

[^1]: This test was successful, but I'm currently in favor of removing it in the final release since it is so large, and it doesn't seem to add much to the game. Perhaps we can add it in a future release, though. I've asked other players for input. (EJM, 2022-11-02)

**Comment by ejm554** [comment]
These mods were added to a pre-release version.
