### ISSUE TITLE
Extra & unneeded files taking up space

### ISSUE THREAD

**Issue by ejm554** [ejm554/gaia-modpack#17]
## Summary
- There are several files in the current modpack repo that are taking up valuable space and serve no value.
- This includes screenshots, logs, (possibly) single-player world files, etc.

## To-Do
- [x] Review and identify the files that meet the criteria above.
- [x] Remove any remaining "Xaero's" artifacts (see #1 ) 
- [x] Remove these files.
