### ISSUE TITLE
Structures spawn too closely & frequently

### ISSUE THREAD

**Issue by ejm554** [ejm554/gaia-modpack#2]
# Overview
- The non-Vanilla structures in the modpack seem (to me) to spawn too frequently.
- The mods that generate structures include:
    - **[Additional Structures](https://www.curseforge.com/minecraft/mc-mods/additional-structures)**
        - [x] Review
        - [x] Don't update [^1]
    - **[Integrated Dungeons and Structures (IDAS)](https://www.curseforge.com/minecraft/mc-mods/idas)**
        - [x] Review
        - [x] Update (see [this comment](https://github.com/ejm554/minor-minors-5/issues/2#issuecomment-1295934723))
        - [x] Re-zip modified datapack
        - [x] Replace old/existing datapack with modified datapack
    - **[Shroom Dealers](https://www.curseforge.com/minecraft/mc-mods/shroom-dealers)** (see also #3 )
        - [x] Review
        - [x] Delete [^2]
    - **[Structory](https://www.curseforge.com/minecraft/mc-mods/structory)**
        - [x] Review
        - [x] Don't update [^1]
    - **[Tinkers Construct](https://www.curseforge.com/minecraft/mc-mods/tinkers-construct)** (Slime islands: 'earth' and 'ocean')
        - - Config info [here](https://github.com/SlimeKnights/TinkersConstruct/wiki/Tinkers%27-Construct-3-FAQ#how-do-i-configure-slime-islands)
        - [x] Review
        - [x] Update (see [this comment](https://github.com/ejm554/minor-minors-5/issues/2#issuecomment-1296066302))
        - [x] Re-jar modified mod file
        - [x] Replace old/existing mod file with modified mod file
    - **[Valhesia Structures](https://www.curseforge.com/minecraft/mc-mods/valhelsia-structures)**
       - [x] Review
       - [x] Update (see [this comment](https://github.com/ejm554/minor-minors-5/issues/2#issuecomment-1295975074))
       - [x] Replace old/existing config file with modified config file

# Other To-Dos
- [x] Add all known structure mods to this Issue.
- [x] Identify the structures that spawn too frequently, along with the associated mod(s).
- [x] Modify files for those structure mods that spawn too frequently.
- [x] Look into what (if anything) can be done about Shroom Traders [^2]
- [x] Test distance between structures, e.g., are they too close or too far? [^3]

[^1]: This mod was reviewed, but a decision was made not to change it. It was likely considered acceptable as-is.
[^2]: According to the dev, the Shroom Traders mod cannot be modified by users. This mod has been deleted. Details in #3 .
[^3]: They were too close. (See [this comment](https://github.com/ejm554/minor-minors-5/issues/2#issuecomment-1299246343).)

**Comment by ejm554** [comment]
## Changes to IDAS

- The following worldgen files were modified to ensure that they spawn less frequently.
- The values in all of them were changed in the same way.
    - i.e., `spacing` and `seperation` values were doubled

### Example

For example, the Labyrinth structure now has these updated values:

![Image](https://user-images.githubusercontent.com/26723535/198847554-e1a8bced-addd-4670-9961-779a1a731d61.png)

The values in the Labyrinth file were previously:

```json
    "spacing": 40,
    "separation": 25
```

### Affected files
_Please note:_ 
- _The filenames for these files would display in the [8.3 format](https://en.wikipedia.org/wiki/8.3_filename) in_ certain _contexts, but not all._
- _The files are located inside the datapack, `idasconfig-1.4.7-1.18.2.zip`._

8.3 Filename Format:
```
\IDASCO~1.2\data\idas\worldgen\STRUCT~1\ABANDO~1.JSO
\IDASCO~1.2\data\idas\worldgen\STRUCT~1\APOTHE~1.JSO
\IDASCO~1.2\data\idas\worldgen\STRUCT~1\BAZAAR~1.JSO
\IDASCO~1.2\data\idas\worldgen\STRUCT~1\BEARCL~1.JSO
\IDASCO~1.2\data\idas\worldgen\STRUCT~1\BEEKEE~1.JSO
\IDASCO~1.2\data\idas\worldgen\STRUCT~1\BRICKH~1.JSO
\IDASCO~1.2\data\idas\worldgen\STRUCT~1\CASTLE~1.JSO
\IDASCO~1.2\data\idas\worldgen\STRUCT~1\COTTAG~1.JSO
\IDASCO~1.2\data\idas\worldgen\STRUCT~1\FARMHO~1.JSO
\IDASCO~1.2\data\idas\worldgen\STRUCT~1\FISHER~1.JSO
\IDASCO~1.2\data\idas\worldgen\STRUCT~1\HAUNTE~1.JSO
\IDASCO~1.2\data\idas\worldgen\STRUCT~1\HERMIT~1.JSO
\IDASCO~1.2\data\idas\worldgen\STRUCT~1\HUNTER~1.JSO
\IDASCO~1.2\data\idas\worldgen\STRUCT~1\LABYRI~1.JSO
\IDASCO~1.2\data\idas\worldgen\STRUCT~1\PILLAG~1.JSO
\IDASCO~1.2\data\idas\worldgen\STRUCT~1\REDHOR~1.JSO
\IDASCO~1.2\data\idas\worldgen\STRUCT~1\TINKER~1.JSO
\IDASCO~1.2\data\idas\worldgen\STRUCT~1\TREETO~1.JSO
\IDASCO~1.2\data\idas\worldgen\STRUCT~1\WITCHE~1.JSO
\IDASCO~1.2\data\idas\worldgen\STRUCT~1\WIZARD~1.JSO
```

Standard Filename Format:

![Image](https://user-images.githubusercontent.com/26723535/198847876-83d3fd78-60b9-4f7a-95fb-55df98b000e0.png)

**Comment by ejm554** [comment]
## Changes to Valhelsia Structures

- The `.minecraft\config\valhelsia_structures-common.toml` file was modified to ensure that all the structures in the mod spawn less frequently.
- The values in all of them were changed in the same way.
    - i.e., `spawn_chance` was reduced by 50%.

### Example

For example, the Castle structure now has an updated spawn chance of `0.25`:

![image](https://user-images.githubusercontent.com/26723535/198852232-24e0c05f-426f-4912-88a2-3a04b0919da8.png)

Previously, the Castle's spawn chance was twice that amount:

```toml
spawn_chance = 0.5
```

**Comment by ejm554** [comment]
## Changes to Tinkers Construct
- The contents of TConstruct-1.18.2-3.5.2.40.jar was unzipped.
- The following were changed by Lisa. 
- In `data/tconstruct/worldgen/structure_set/`, the following files were edited:
    - `overworld_ocean_island.json`
    - `overworld_sky_island.json`
- Each of those files had a key called `structures`. 
- `slime islands` were removed from the arrays that were the values of those keys

## Details
### overworld_ocean_island.json
Regular path: `data/tconstruct/worldgen/structure_set/overworld_ocean_island.json`
8.3 Format path: `\data\TCONST~1\worldgen\STRUCT~1\OVERWO~1.JSO`

Before:
![image](https://user-images.githubusercontent.com/26723535/198859433-a1f31579-1aed-485a-98f0-305de27560f1.png)
After:
![image](https://user-images.githubusercontent.com/26723535/198859435-3f31f69a-89d5-46e6-b5b4-258096e08ee6.png)

### overworld_sky_island.json
Regular filepath: `data/tconstruct/worldgen/structure_set/overworld_sky_island.json`
8.3-Format filepath: `\data\TCONST~1\worldgen\STRUCT~1\OVERWO~2.JSO`

Before:
![image](https://user-images.githubusercontent.com/26723535/198859569-a49adbc0-b877-4f48-8b8f-a4b7aee6e911.png)
After:
![image](https://user-images.githubusercontent.com/26723535/198859575-9dd154d8-3706-489e-aa5c-8d8be00bd9c4.png)

**Comment by ejm554** [comment]
## More about IDAS

Following the changes made 3 days ago (~10-29), I discovered that two hermit's houses spawned too closely. They are within the average distance of 30 in the config file, so the numbers of the config files probably need to be increased again.

![Image](https://user-images.githubusercontent.com/26723535/199346922-5ff366b5-686f-4cf0-9c63-8b744fe1ab57.png)

![Image](https://user-images.githubusercontent.com/26723535/199347404-307d9f60-ce94-4475-8684-8568315deeb0.png)

**Comment by ejm554** [comment]
## More about IDAS
_In preparation for MM-2022-306a_

**The `spacing` and `separation` values were doubled *again* for the same set of files, i.e., they were increased to _four_ times of their original values.**

![image](https://user-images.githubusercontent.com/26723535/199622631-6aa09b47-bbee-471b-bff6-1b5304970b77.png)

![image](https://user-images.githubusercontent.com/26723535/199622645-d2d9d94d-acab-4406-bb58-652fd41750a4.png)

---
**The numbers found in the Brickhouse file, prior to being increased, seem suspect. As I understand the `seperation` value should be smaller than `spacing.` I'm not sure if this indicates on error on my part, or if they were weird to begin with.**

![image](https://user-images.githubusercontent.com/26723535/199622013-27103319-228c-48fd-adac-d4998b7b797f.png)

The new values are as follows:
```
    "spacing": 60,
    "separation": 40
```
---
**I noticed an issue with the IDAS folder that I zipped in a previous release. It contained an intermediary folder (number 2 in the screenshot). It's unclear if/how this caused a problem with how the mod worked. Given that the hobbit buildings were generating, it seems reasonable that it was working. I will try to correct this problem in the next release.**

![image](https://user-images.githubusercontent.com/26723535/199624336-a8e6e854-0f77-486c-b525-de67226cfcf5.png)
