### ISSUE TITLE
Task list for version 2.0.0

### ISSUE THREAD

**Issue by ejm554** [ejm554/gaia-modpack#37]
## Overview
This issue lists changes for the next iteration (v2.0.0) of the modpack.

## Update
- [x] Do: #43
- [x] Do: #44

## Add
- [x] [Crying Portals mod](https://www.curseforge.com/minecraft/mc-mods/crying-portals)
- [x] [Chalk mod](https://www.curseforge.com/minecraft/mc-mods/chalk)
- [x] CC peripherals
    - [Advanced Peripherals](https://www.curseforge.com/minecraft/mc-mods/advanced-peripherals)
    - [More Peripherals](https://www.curseforge.com/minecraft/mc-mods/more-peripherals)
- [x] Camera / recording (similar to Replay mod)
    - Maybe [CMDCam](https://github.com/CreativeMD/CMDCam)
- [x] Paintings tools
    - [Paintings++ mod](https://www.curseforge.com/minecraft/mc-mods/paintings)
    - [Painting Pack Maker app](https://github.com/AbsolemJackdaw/PaintingPackMaker)
- [x] Paintings++ resourcepack and/or configurations
    - See [documentation](https://github.com/AbsolemJackdaw/Paintings--/wiki/Adding-Paintings-1.16-and-up).
    - See initial resource pack: GaiaPaintingPack-2022-333.zip

~~[Stack Refill mod](https://www.curseforge.com/minecraft/mc-mods/stack-refill)~~  *(Already exists in modpack)*

## Remove
- [x] Straw Golem
  - See: #35 
  - Official issue here: https://github.com/t2pellet/strawgolem/issues/105.

~~`chunkinfo` command~~
  - *Maybe* possible via [WorldEdit permissions](https://worldedit.enginehub.org/en/latest/commands/?highlight=chunkinfo#chunk-commands).

## Don't Forget To...
- [ ] Remove config file for Straw Golem on server
- [ ] If MultiMC.cfg file is on server, remove or edit

**Comment by ejm554** [comment]
## Example of paintings added with Paintings++ mod via Painting Pack Maker app and a custom resource pack
![2022-11-29_21 26 16](https://user-images.githubusercontent.com/26723535/205161816-9bc32c45-f6e1-4ab0-bc36-97f527367720.png)
