### ISSUE TITLE
Using the earthbore gauntlet causes local game to crash

### ISSUE THREAD

**Issue by ejm554** [ejm554/gaia-modpack#8]
# Overview
- A user reported that use of the earthbore gauntlet causes the local game to crash.
- This item is part of Mowsie's Mobs.
- This is a bug, according to the [Mowsie's Mobs GitHub](https://github.com/BobMowzie/MowziesMobs/issues/667).
    - Other animated items from the mod may also cause crashing (ferrous wroughtnaught axe, heliomancy laser blast).
    - The dev suggested that users running 1.5.29 of the mod update it to 1.5.30.
    - We are already running 1.5.30, however, so it is unclear why we are also encountering the issue.

# To-Do
- [x] See if the problematic tools can be disabled, such as via a config file. [^1]
- [x] See if there is another suggested fix, such as a patch or update.
- [x] Update Mowsie's Mobs mod to 1.5.31.

[^1]: I looked through `mowziesmobs-client.toml` and `mowziesmobs-common.toml`, and I didn't find any options to disable specific items.

**Comment by ejm554** [comment]
There was an update to the mod on 2022-10-25 (1.5.30 -> 1.5.31), so I will plan to update our modpack. It's not clear whether it will resolve the issue, however. The changelog to the [newer version](https://www.curseforge.com/minecraft/mc-mods/mowzies-mobs/files/4051446) simply said, "Update to newer versions of Geckolib."
